# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\choise_figure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choise_dialog(object):
    def setupUi(self, Choise_dialog):
        Choise_dialog.setObjectName("Choise_dialog")
        Choise_dialog.resize(400, 80)
        Choise_dialog.setMinimumSize(QtCore.QSize(400, 80))
        Choise_dialog.setMaximumSize(QtCore.QSize(400, 80))
        self.verticalLayout = QtWidgets.QVBoxLayout(Choise_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Choise_dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Choise_dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Choise_dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Choise_dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(Choise_dialog)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Choise_dialog)
        QtCore.QMetaObject.connectSlotsByName(Choise_dialog)

    def retranslateUi(self, Choise_dialog):
        _translate = QtCore.QCoreApplication.translate
        Choise_dialog.setWindowTitle(_translate("Choise_dialog", "ВЫБОР ФИГУРЫ"))
        self.label.setText(_translate("Choise_dialog", "Выберите фигуру, которой станет пешка:"))
        self.pushButton.setText(_translate("Choise_dialog", "Ферзь"))
        self.pushButton_2.setText(_translate("Choise_dialog", "Слон"))
        self.pushButton_3.setText(_translate("Choise_dialog", "Конь"))
        self.pushButton_4.setText(_translate("Choise_dialog", "Ладья"))
