# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\choise_figure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choise_dialog(object):
    def setupUi(self, Choise_dialog):
        Choise_dialog.setObjectName("Choise_dialog")
        Choise_dialog.resize(400, 80)
        Choise_dialog.setMinimumSize(QtCore.QSize(400, 80))
        Choise_dialog.setMaximumSize(QtCore.QSize(400, 80))
        self.verticalLayout = QtWidgets.QVBoxLayout(Choise_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Choise_dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Queen = QtWidgets.QPushButton(Choise_dialog)
        self.Queen.setObjectName("Queen")
        self.buttonGroup = QtWidgets.QButtonGroup(Choise_dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Queen)
        self.horizontalLayout.addWidget(self.Queen)
        self.Bishop = QtWidgets.QPushButton(Choise_dialog)
        self.Bishop.setObjectName("Bishop")
        self.buttonGroup.addButton(self.Bishop)
        self.horizontalLayout.addWidget(self.Bishop)
        self.Knight = QtWidgets.QPushButton(Choise_dialog)
        self.Knight.setObjectName("Knight")
        self.buttonGroup.addButton(self.Knight)
        self.horizontalLayout.addWidget(self.Knight)
        self.Rook = QtWidgets.QPushButton(Choise_dialog)
        self.Rook.setObjectName("Rook")
        self.buttonGroup.addButton(self.Rook)
        self.horizontalLayout.addWidget(self.Rook)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Choise_dialog)
        QtCore.QMetaObject.connectSlotsByName(Choise_dialog)

    def retranslateUi(self, Choise_dialog):
        _translate = QtCore.QCoreApplication.translate
        Choise_dialog.setWindowTitle(_translate("Choise_dialog", "ВЫБОР ФИГУРЫ"))
        self.label.setText(_translate("Choise_dialog", "Выберите фигуру, которой станет пешка:"))
        self.Queen.setText(_translate("Choise_dialog", "Ферзь"))
        self.Bishop.setText(_translate("Choise_dialog", "Слон"))
        self.Knight.setText(_translate("Choise_dialog", "Конь"))
        self.Rook.setText(_translate("Choise_dialog", "Ладья"))
